### ISSUE TITLE
Can Compressed Output be a runtime option?

### ISSUE THREAD

**Issue by JohnOmernik** [cisco/joy#100]
I understand it has to be compiled in. But can we compile it in, and allow put a setting in the config to determine whether it's enabled or not?  I didn't set the compressed out and am getting compressed output...

**Comment by JohnOmernik** [comment]
Not to mention, tests fail when you set compressed output to 0

Thu Sep 14 18:46:30 UTC 2017 info: 104 packets, 0 active records, 39 records output, 0 alloc fails, 1.7256e+07 bytes/sec, 1.0400e+05 packets/sec, 3.9000e+04 records/sec
error: could not parse argument 
Traceback (most recent call last):
  File "/app/joy/test/run_tests.py", line 165, in <module>
    test()
  File "/app/joy/test/obsidianbox/test_general.py", line 146, in main_general
    test_unix_os()
  File "/app/joy/test/obsidianbox/test_general.py", line 115, in test_unix_os
    validate_general.run()
  File "/app/joy/test/obsidianbox/test_general.py", line 92, in run
    for line in f:
  File "/usr/lib/python2.7/gzip.py", line 464, in readline
    c = self.read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 303, in _read
    self._read_gzip_header()
  File "/usr/lib/python2.7/gzip.py", line 197, in _read_gzip_header
    raise IOError, 'Not a gzipped file'
IOError: Not a gzipped file
make: *** [test] Error 1
Makefile:77: recipe for target 'test' failed

**Comment by fliphil** [comment]
The definitions of the z macros in src/include/output.h change depending on what the COMPRESSED_OUTPUT is set to at compile time. Due to that design, it cannot be a runtime option because compilation comes before the program is able to execute.

If you need the tests to work with uncompressed files, could you please submit a fix in a pull-request?

Thanks!

**Comment by JohnOmernik** [comment]
@fliphil I don't have the technical expertise to write a test for non-compressed output. Being that the COMPRESSED vs. Non Compressed is documented in the readme, I would think that the tests should work.  Is there a way to compile (make, make install) without running tests if the NONCOMPRESSED won't be fixed without external contribution?

**Comment by fliphil** [comment]
The benefit of GitHub is that everyone can work together to make the software better, hence why I asked if you were able to provide a fix.
Until a fix is made, you can go into Makefile to remove the portions where it calls test under the "make install" target. Alternatively, you can call "make" and then ./install/install-sh.
