### ISSUE TITLE
Trick to only getting log output in the output file

### ISSUE THREAD

**Issue by JohnOmernik** [cisco/joy#109]
I have gotten the logging to a file, unbuffered working etc... however I am running into an issue where there seems to be a  record on start, written to the output location, (instead of the logfile location) that is causing me some issue as the schema is very different from the output records... i.e. This is written:

{"version":"1.72","interface":"intf11","promisc":1,"output": ...

 and then next record is

{"sa":"172.17.0.2","da":"192.168.0.105","pr":6,"sp":59518,"

To me, that first example should be in logfile, and the second in output, and out should be somewhat consistent in what is produced... does that make sense?

I do have verbosity = 1 right now, but that shouldn't matter, right? the first record is not packet output, it's summary about the start of the application, or am I looking at this incorrect? 

Thanks!

**Comment by fliphil** [comment]
The first JSON object represents the settings state that Joy ran with at the time that the file was made. This is to help with search and identification of data within the file. It is inside the file so that the settings info and data itself is coupled together for easy access.

Either skipping the first object, or checking if the "sa" key is contained within the object are a couple of ways to filter out the settings information while doing a load of the data.

**Comment by JohnOmernik** [comment]
Interesting approach, as a data scientist, I find it a bit odd, as it appears you are creating a log file for human consumption, and then relying on computers to specify the exception for processing, I would error on the other direction. (i.e. doing something in the "log" file that specifies settings and if  a human needs that data they can look it up) I will alter my processing tools to work around this. An option to write this header to the logfile instead of the data file may be good for future thought.

**Comment by fliphil** [comment]
If it were written to a logfile, the settings information could be lost and then there's a whole process that needs to be created for mapping the logfile to each JSON file. It is much simpler to keep them together in the same file.

**Comment by JohnOmernik** [comment]
But what actually happens more? Settings changes or times a human needs to look it up the settings or something that needs to process the logs, and has to handle that out of character log request?  You are emphasizing a need that in production could be the opposite depending on the environment. If someone was running this in a data collection/logging mode, the settings would not be changing.  So why not have an option and let the user choose which pain point they wish to operationalize?

On a side note,  I am finding the response to suggestions of people trying to to use this tool puzzling... it's like you have decided there is one way to use the tool, and suggestions like mine are being closed instead of even being left open as ideas for people to contribute. While I can disagree on the idea that anyone who has an idea should be the implementer (I feel that as a data scientist, my ideas are solid, but the ability for me to implement them will not be ideal, thus a response of "create a pull request" for every idea seems to disincentivize community ideation.. but that's only my opinion and I understand it's not shared by all), I don't think ideas like mine which are in "how the product could be used" is something that should be closed as you did.  I may not be able to implement it, but why close the idea? Others may see it, others with more skills... the alternative use case to how you see the tool may resonate with others... why not leave it open?
