### ISSUE TITLE
Filter to compare string values

### ISSUE THREAD

**Issue by simonstruk** [cisco/joy#116]
Hello, it would be useful to have a filter for comparing string values, e.g.
--where "tls_sec{seclevel{classification}} = legacy"
or
--where 'tls_sec{seclevel{classification}} = "legacy"'
These don't work ATM

**Comment by fliphil** [comment]
Thanks, we'll look at this and see if there is a bug or if new functionality should be added. If you spot a fix before we do, definitely let us know!

**Comment by davidmcgrew** [comment]
First, let me describe a workaround: use two joyq passes over the data files, in which the first pass uses —tls_sec to enrich the JSON records with the info about the security of the TLS sessions, and the second session uses the —where argument to select a particular classification, such as “legacy”, like this:

mcgrew@altair:~/joy$ ./joyq ./test/pcaps/*.pcap --tls_sec > tmp.json
mcgrew@altair:~/joy$ ./joyq tmp.json --select tls_sec --where "tls_sec{seclevel{classification}}=legacy"
{"tls_sec": {"seclevel": {"concerns": ["CA not trusted: Internet Widgits Pty Ltd", "hash - SHA"], "classification": "legacy"}}}
{"tls_sec": {"seclevel": {"concerns": ["CA not trusted: Internet Widgits Pty Ltd", "hash - SHA"], "classification": "legacy"}}}

The reason that this doesn’t work in a single pass is that the —tls_sec enrichment is performed after the —where filtering within joyq.

What change should we make to joyq?   Good question.   We could reverse the order of enrichment and filtering, but that would make it impossible to filter prior to enrichment.   Alternatively, we could introduce a convention such as: the order of the enrichment and filtering will reflect the order in which the arguments appear on the command line.   That might be the best way to do it.

thanks

David

**Comment by simonstruk** [comment]
You are right, it makes sense now. Thanks!
