### ISSUE TITLE
Direction of traffic

### ISSUE THREAD

**Issue by aradford123** [cisco/joy#12]
I am curious as to how traffic direction is calculated.

I have .pcap from a lab where there are private IP addresses used.  
I used ./bin/pcap2flow  bidir=1 http=1 dns=1 tls=1 dist=1 to generate the flows.

Below seems to indicate there are 2664 flows inbound from an external source port of 443 into my lab.

If i look at wireshark, it indicates traffic is outbound.

$ ./joy/query.py --select "sa, sp, da, dp, ib,ip,ob,op,dns" --where 'da=192.168.1.106' ./joy/fullDay.json.gz | wc -l
    2664
$ ./joy/query.py --select "sa, sp, da, dp, ib,ip,ob,op,dns" --where 'sa=192.168.1.106' ./joy/fullDay.json.gz | wc -l
       6
$ ./joy/query.py --select "sa, sp, da, dp, ib,ip,ob,op,dns" --where 'da=192.168.1.106' ./joy/fullDay.json.gz | head
{
"name": [
    {  "sa":  "52.x.x.x" ,  "sp":  443 ,  "da":  "192.168.1.106" ,  "dp":  46330 ,  "ib":  2828 ,  "ip":  31 ,  "ob":  74 ,  "op":  31 } ,
    {  "sa":  "52.x.x.x" ,  "sp":  443 ,  "da":  "192.168.1.106" ,  "dp":  46330 ,  "ib":  2918 ,  "ip":  32 ,  "ob":  74 ,  "op":  32 } ,

**Comment by davidmcgrew** [comment]
These are almost certainly continuations of flows that had an active timeout.   We need some better options for dealing with this.   I propose:

- the query program should be able to detect and stitch together continuations of flows
- the joy program should be run-time configurable to either not do any active timeouts, or to have a configurable active timeout (say "active_timeout=3600" would give one hour).  

Comments welcome.

**Comment by fliphil** [comment]
I believe this has been addressed in the latest Sleuth implementation.
