### ISSUE TITLE
Parsing of large records

### ISSUE THREAD

**Issue by simonstruk** [cisco/joy#130]
Hello,
Joy doesn't parse TLS records that span over multiple packets, e.g handshake record with server hello and  multiple certificates. The parsing doesn't pass the condition at tls.c:1787.
Are there any plans to implement this in the near future?

**Comment by fliphil** [comment]
Hello! Just to make sure that I understand your problem correctly, you are saying that the TLS messages are being segmented into multiple smaller packets. This is resulting in cases where the TLS message headers have a length greater than the actual packet size (i.e. 3000 > 1500), and this is causing the sanity check at tls.c:1787 to fail.

**Comment by simonstruk** [comment]
Exactly. It happens when there are multiple messages inside one TLS handshake record. Admittedly, it might be a rare case.

**Comment by simonstruk** [comment]
By stepping through the code, I noticed that Joy does this sanity check even when dealing with continuation packets, but in that case there is no TLS header (usually it starts somewhere in the middle of a certificate) and thus the tls_len is determined wrongly and may or may not return from tls_update without copying the rest of the certificate data to the buffer for later parsing. (This is a different case than what I described earlier, but more prominent in regular HTTPS traffic)

**Comment by fliphil** [comment]
Thanks for looking at this in detail. I've also come to the same conclusions upon inspection in GDB. I think ultimately the solution will be to keep track of the segmentation state of the messages in order to piece the whole TLS message together when it is spread over multiple packets. Implementing the segmentation state stacking for TLS is on our work board, we hope to have that completed sometime in the near future :)

Is this something that you are interested in to implement? It sounds like you know your way around the code, and it would be great to have your help in getting this done sooner!

**Comment by fliphil** [comment]
I made an attempt at fixing this. Please take a look at this branch to see if it helps:
https://github.com/cisco/joy/tree/tls-continuity

**Comment by simonstruk** [comment]
The ServerHello message is now parsed, but the certificate part is not. I think the problem is not looking at the lengths of the messages and not handling 3-packet-long messages correctly. Maybe a Wireshark screenshot will help better explain what I have in mind. Here, the r->segmented becomes something over 3000 in the first packet and then it makes a mess when parsing the second packet (start points somewhere beyond the end of the packet, rem_len underflows).

![screenshot from 2017-11-21 10-32-42](https://user-images.githubusercontent.com/14001237/33065337-d58fa15c-cea8-11e7-9e07-7deee30e367e.png)

This might require a more thorough revision of the code... on the other hand, the very fact that the messages are constructed in this way may be a good indicator that something is amiss. (this is botnet traffic)

**Comment by fliphil** [comment]
I added a new commit to address multiple handshake messages when looking for the certificates. Could you verify that solves the cert problem? I think we still need to add a logic clause within the r->segmented block (right before line 1772) to check if the segmentation amount is greater than the packet size. Something like:

`if (r->segmented >= rem_len) { r->segmented -= rem_len; return; }`

Could you see if making that modification works with your PCAP?
