### ISSUE TITLE
Make "Undefined symbols for architecture x86_64" error

### ISSUE THREAD

**Issue by anish-shekhawat** [cisco/joy#131]
OS Version: macOS High Sierra 10.13

$ ./config
Checking for required dependencies
Checking for libpcap...exists
Checking for libcrypto...exists
Checking for libz...exists
Checking for libcurl...exists
Checking for libpthread...exists
Searching for OpenSSL headers...found
Searching for Curl headers...found
All dependencies found. Issue 'make clean;make' to build the code

$ make
Makefile variables:
buildroot=joy
sysname=DARWIN
version=1.73
cwd=src
gcc -Wall -Wno-deprecated-declarations -g -O3   -DDARWIN=1 -DVERSION=\"1.73\" -o "/Users/anish/Documents/SJSU/CS297/Code/joy/bin/joy" -I ./include -I "/usr/local/Cellar/openssl/1.0.2l/include" -I "/usr/include" joy.c p2f.c config.c osdetect.c anon.c pkt_proc.c nfv9.c tls.c classify.c radix_trie.c hdr_dsc.c procwatch.c addr_attr.c addr.c wht.c http.c str_match.c acsm.c dns.c example.c updater.c ipfix.c ssh.c ike.c ip_id.c salt.c parson.c fingerprint.c ppi.c utils.c dhcp.c -L "/usr/lib" -lpcap      -lm        -lcrypto   -lcurl     -lpthread  -lz
Undefined symbols for architecture x86_64:
  "_X509_get0_signature", referenced from:
      _tls_x509_get_signature in tls-7260b4.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [joy] Error 1
make: *** [all] Error 2

**Comment by bhudson33** [comment]
Make sure you are using the correct headers for the OpenSSL library version you are linking against. This looks like an OpenSSL v1.1.0 vs older versions linker error.

Cheers,
Bill.

The ’S’ in ‘IoT’ stands for Security.



On Nov 6, 2017, at 3:16 AM, Anish Singh Shekhawat <notifications@github.com<mailto:notifications@github.com>> wrote:


OS Version: macOS High Sierra

$ ./config
Checking for required dependencies
Checking for libpcap...exists
Checking for libcrypto...exists
Checking for libz...exists
Checking for libcurl...exists
Checking for libpthread...exists
Searching for OpenSSL headers...found
Searching for Curl headers...found
All dependencies found. Issue 'make clean;make' to build the code

$ make clean;make
rm -f cscope.out cscope.files
rm -f /Users/anish/Documents/SJSU/CS297/Code/joy/doc/joy.txt
find . -name '.pyc' -delete
rm -rf "/Users/anish/Documents/SJSU/CS297/Code/joy/bin/"
Makefile variables:
buildroot=joy
sysname=DARWIN
version=1.73
cwd=src
gcc -Wall -Wno-deprecated-declarations -g -O3 -DDARWIN=1 -DVERSION="1.73" -o "/Users/anish/Documents/SJSU/CS297/Code/joy/bin/joy" -I ./include -I "/usr/local/Cellar/openssl/1.0.2l/include" -I "/usr/include" joy.c p2f.c config.c osdetect.c anon.c pkt_proc.c nfv9.c tls.c classify.c radix_trie.c hdr_dsc.c procwatch.c addr_attr.c addr.c wht.c http.c str_match.c acsm.c dns.c example.c updater.c ipfix.c ssh.c ike.c ip_id.c salt.c parson.c fingerprint.c ppi.c utils.c dhcp.c -L "/usr/lib" -lpcap -lm -lcrypto -lcurl -lpthread -lz
Undefined symbols for architecture x86_64:
"_X509_get0_signature", referenced from:
_tls_x509_get_signature in tls-7260b4.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [joy] Error 1
make: *** [all] Error 2

**Comment by fliphil** [comment]
Thank you for reporting this, it appears that in adding support for OpenSSL 1.1.0, we introduced some symbols that are not available in earlier versions of the library. I'll work on a fix for this, hope to have it completed soon.

Phil

**Comment by anish-shekhawat** [comment]
Thank you so much! That fixed it!
