### ISSUE TITLE
Report more than 200 packets for a flow

### ISSUE THREAD

**Issue by xiaoming1999** [cisco/joy#142]
Is it possible to report per packet information (ppi) for more that 200 packets for a flow? The MAX_NUM_PKT_LEN is defined to be 200. 

If the flow has more than 200 packets, does Joy save packet information for all the packets or does it just save the packet information for the first 200 packets?

Thanks a lot,

Xiaoming

**Comment by fliphil** [comment]
Hello Xiaoming,

I believe it will stop saving the information if 200 packets is reached. This is because the array is statically defined to only have 200 slots in memory, so it cannot go over that amount.

Thanks,
Phil

**Comment by xiaoming1999** [comment]
Hi Phil,

Thanks a lot for your quick response.

We would like to capture per packet info for all packets. 

Regards,

Xiaoming

**Comment by fliphil** [comment]
In the short term, you could increase the value for that macro. You will see the memory usage increase accordingly, but will have room for more data.
Alternatively, you could implement a list structure and dynamically allocate/delete the memory to expand and shrink as needed. We are working on other stuff at the moment, so you would need to do this yourself if memory is an issue.

Hope that helps,
Phil

**Comment by xiaoming1999** [comment]
This helps a lot.
