### ISSUE TITLE
model.py: TLS params

### ISSUE THREAD

**Issue by simonstruk** [cisco/joy#153]
Hello,
I see in model.py that there is some code for creating logistic regression paramteres with TLS information included, but there is no option to enable that. Is there some reason for this? Does the code otherwise work?

**Comment by fliphil** [comment]
Hello Simon,

The model.py code was made to demo some functionality within Joy, hence no direct option to enable it currently. The code should work, but please be aware that we haven't performed testing so it is possible that you could encounter issues.

Philip
