### ISSUE TITLE
First 8 bytes of body not being shown correctly

### ISSUE THREAD

**Issue by jsbalaquit** [cisco/joy#159]
Sometimes, instead of the actual first bytes of the body, all that can be seen in the body field is '2e00'. Is this intended?

**Comment by davidmcgrew** [comment]
Can you please provide more details?   What is the HTTP body in the case that you are describing here?

thanks

David

**Comment by jsbalaquit** [comment]
Hi David,

The body consists of non-ASCII bytes, with content-length 192. I'm pasting the dump from wireshark:

0000012B  35 be 53 88 f0 ab fd d6  9a 18 87 ff 6d 11 9e b3 5.S..... ....m...

0000013B  7a 6f 66 cb 71 c7 ac ad  f7 bc 5b 29 91 e4 cf 66 zof.q... ..[)...f

0000014B  d0 9f dc 28 d8 c7 e9 ef  ae 2a bd 5f 30 c5 7b ab ...(.... .*._0.{.

0000015B  a6 4e 37 c2 b7 b3 be 7c  00 d7 63 3f 99 9c 64 f8 .N7....| ..c?..d.

0000016B  25 72 6a 54 ab a8 b1 16  bf 41 8f 37 6b ba 95 a3 %rjT.... .A.7k...

0000017B  37 31 b8 ef 91 35 c6 0f  61 98 c5 8e 19 1a 8c ed 71...5.. a.......

0000018B  1f 99 25 c8 24 71 9d 02  ff 2f a5 fc 5c f1 d6 ed ..%.$q.. ./..\...

0000019B  3e b4 65 aa b8 7b 9b b6  e6 e3 09 c8 d3 c6 d4 29 >.e..{.. .......)

000001AB  c5 2f 00 d6 2c e0 e6 28  f2 d6 36 ed bd d5 30 c2 ./..,..( ..6...0.

000001BB  9d 9a 13 fa bc 1e ce dd  61 ea 22 30 61 41 66 b1 ........ a."0aAf.

000001CB  6a 4e 3c 88 c5 3e ac 08  d2 f3 7f f0 b2 32 df 6c jN<..>.. .....2.l

000001DB  f8 10 f8 b8 68 1f 65 2b  ff 3c 16 11 35 93 b6 44 ....h.e+ .<..5..D

The byte distribution array seems to be accurate for the body, but instead of the first bytes, I only get "2e00" from the JSON file output.

**Comment by bhudson33** [comment]
This issue has been resolved with the latest commit.
