### ISSUE TITLE
Analyzing CAPWAP Traffic

### ISSUE THREAD

**Issue by kkashwin2** [cisco/joy#177]
Is there a way we can make Joy analyze the CAPWAP traffic payload (assuming its unencrypted) ?

**Comment by bhudson33** [comment]
The CAPWAP protocol could be added to Joy in the same fashion that the other protocols have been added. We currently do not have CAPWAP on our immediate radar, but please do feel free to implement and submit your code to the github repository. This is the beauty of open source. Something you find useful now others may also find useful. An easy way to add the CAPWAP protocol would be to follow the "example.h" in the repo or look at some of the other protocols (ssh, http, dns, etc). Essentially, you have a macro to create the necessary prototypes. The Joy main logic will automatically include the new protocol for processing if it is added to the protocol list. You will simply have to write the processing module for CAPWAPafter defining it and adding it to the feature list.

**Comment by kkashwin2** [comment]
Sure! Thanks for the pointer. We will check out example.h and see if there is a way to incorporate CAPWAP.
