### ISSUE TITLE
No example or proper documentation

### ISSUE THREAD

**Issue by ahmetturkmen** [cisco/joy#186]
I am trying to use the scripts which are in analysis folder but there is no example files to test those commands which are described in README file.

**Comment by fliphil** [comment]
Hello,

You can see some example usage in the docs/workbench.pdf file.
Hope that helps!

**Comment by ahmetturkmen** [comment]
Hello, 

Thank you for your help. I actually investigated that file but I meant that there is no example file to test model.py, as the [README](https://github.com/cisco/joy/blob/master/analysis/README) describes that we have to Positive Examples ( JSON Format) and Negative Examples (JSON Format), it might be good idea to have some example json files in order to test the scripts. 

Best Regards.
