### ISSUE TITLE
no VLAN support for data link type 12

### ISSUE THREAD

**Issue by TornadoBoy** [cisco/joy#189]
I tried to use joy to parse a pcap file of raw packets. Unfortunately, it output "error: could not parse filter ip or vlan: no VLAN support for data link type 12".  How can I fix that? 
If not possible, is there any other tool which can parse pcap of raw packets?

**Comment by bhudson33** [comment]
this error is coming from libpcap. As you can see here https://linux.die.net/man/7/pcap-linktype, libpcap does not support a link type of 12. I am curious, what kind of link layer do you believe the packets are using? Do you have the cap file of the data and can it be sent to us for examination?

**Comment by TornadoBoy** [comment]
Actually, my pcap files are made of raw packets without link layers. I intuitively thought parsing raw IP packets would not be a problem. The cap file of the data is captured from TUN interface in a phone. It's OK to send you the file for examination. What I do concern is how to fix the problem. Any suggestions?

**Comment by TornadoBoy** [comment]
It's quite simple to modify _process_packet()_ to feed raw IP packets. The previous problem is actually caused by calling _pcap_compile()_ when reading a pcap file in _process_pcap_file()_. I don't see why _pcap_compile()_ fails  when feeding LINKTYPE_RAW files. So I had to delete the set-filter part in my code.

**Comment by bhudson33** [comment]
Glad you found a workaround. If you could send along your diffs, we can take a look at them and see what we can incorporate into the repo. Thanks!

**Comment by bhudson33** [comment]
closed per work around

**Comment by oasiszrz** [comment]
I have encounter the same problem for some loopback packets with just 0x20000000 flag in eth layer. Also i have to remove the set-filter part and process this flag in process_packet like:
```
uint32_t loopback_flag = htonl(*(const uint32_t *)(packet + 0));
if(loopback_flag == 0X02000000){...}
```
