### ISSUE TITLE
Error: could not parse filter ip or vlan: no VLAN support for data link type 113

### ISSUE THREAD

**Issue by decaby7e** [cisco/joy#196]
After passing a pcap file through joy, I am returned with this error:

`error: could not parse filter ip or vlan: no VLAN support for data link type 113`

Any help would be appreciated. I can submit further information if needed.

**Comment by bhudson33** [comment]
This error comes from the libpcap library and not the joy code base itself. It appears you have a data link type that isn't supported by libpcap. I would look into the libpcap documentation and see if there is something there that can help you get past this error.

**Comment by bhudson33** [comment]
closing issues due to libpcap limitation and work around discovered.

**Comment by shaw827** [comment]
I get the same issue. I will appreciate if you could post the workaround.

**Comment by gproman** [comment]
I too have the same issue and would appreciate if someone could post the workaround.

**Comment by decaby7e** [comment]
I cannot recall the exact steps that I took to resolve this but I would like to say that I was passing Joy the incorrect file format. So I was saving a PCAPNG rather than a PCAP. I would recommend trying the tool with sample PCAPs from online somewhere and seeing if that causes the same error to be thrown.
