### ISSUE TITLE
Problem with build joy on mac os

### ISSUE THREAD

**Issue by forgit12** [cisco/joy#199]
Hi, I have some problem with build joy on mac os (High Sierra version 10.13.3)

After I run ./config
and run make

Building libjoy.so ...
rm: /Users/oborysen/joy_project/joy1/lib/libjoy.so.3.0.0-dev.dSYM: is a directory
make[1]: *** [libjoy.so] Error 1
make: *** [all] Error 2
<img width="1883" alt="screen shot 2018-08-10 at 6 41 44 pm" src="https://user-images.githubusercontent.com/26071733/43967505-34279380-9ccd-11e8-8195-530c7912264b.png">

**Comment by bhudson33** [comment]
I am running 10.13.6 and do not have any issues. It seems like from the error that an "old" directory is laying around from a prior build of the shared library objects. Try 'make clean' and then run 'make' again to see what you get.

**Comment by forgit12** [comment]
@bhudson33 Thank you I try it once more and find one more issue
when I do make
see the mistake
ld: library not found for -lcrypto

openssl is already installed
I add also linked using ln -s
I searched that on mac I can fix it by using -L {path_to_my_ssl_lib_dir}

But to add this flag need to edit MAKEFLAGS variable in Makefile
Or maybe you know another way to fix it.

Thank you

**Comment by bhudson33** [comment]
when you issue the ./config command, you can specify the path to the library on the command line. That will include your "custom" path in the make variables. Like this:

./config -l {path_to_your_ssl_lib_dir}

Then when you issue make, it should find everything.

Also, curious, when you issue the command
./config

does it find everything? It should tell you if it does or not like so:
bhudson-mac:9>./config
Checking for required dependencies
Checking for libpcap...exists
Checking for libcrypto...exists
Checking for libcurl...exists
Checking for libpthread...exists
Checking for libz...exists
Searching for OpenSSL headers...found
Searching for Curl headers...found
The following variables were defined:
export LIBPATH= -L "/usr/lib" -L "/usr/local/lib"
export SSLPATH= -I "/usr/local/ssl/include"
export CURLPATH= -I "/usr/local/include"
export COMPDEF= -DUSE_GZIP
export COMPRESSED= -DCOMPRESSED_OUTPUT=1
All dependencies found. Issue 'make clean;make' to build the code

**Comment by forgit12** [comment]
Below is sample of my output
Checking for required dependencies
Checking for libpcap...exists
Checking for libcrypto...exists
Checking for libcurl...exists
Checking for libpthread...exists
Checking for libz...exists
Searching for OpenSSL headers...found
Searching for Curl headers...found
The following variables were defined:
export LIBPATH= -L "/usr/lib"
export SSLPATH= -I "/Users/sasha/.brew/Cellar/openssl/1.0.2o_2/include/"
export CURLPATH= -I "/opt/vagrant/embedded/include"
export COMPDEF= -DUSE_GZIP
export COMPRESSED= -DCOMPRESSED_OUTPUT=1
All dependencies found. Issue 'make clean;make' to build the code

I try different flags and dir location, but also I see this mistake after make
ld: library not found for -lcrypto

**Comment by bhudson33** [comment]
I am guessing based on the output it is finding crypto library in /usr/lib but the header files it is including are from the brew install. Add the path to the crypto library for the brew install to your config command and see how that goes.

**Comment by forgit12** [comment]
I solve the problem with next steps:
1. see information about lib by type `brew info openssl`
2. copy information from description
```
For compilers to find this software you may need to set:
    LDFLAGS:  -L/Users/user1/.brew/opt/openssl/lib
    CPPFLAGS: -I/Users/user1/.brew/opt/openssl/include
For pkg-config to find this software you may need to set:
    PKG_CONFIG_PATH: /Users/user1/.brew/opt/openssl/lib/pkgconfig
```
3. then manually edit file  config.vars in joy directory and put right way to lib and headers like this
```
export LIBPATH= -L "/Users/user1/.brew/opt/openssl/lib"
export SSLPATH= -I "/Users/user1/.brew/opt/openssl/include"
export CURLPATH= -I "/opt/vagrant/embedded/include"
export COMPDEF= -DUSE_GZIP
export COMPRESSED= -DCOMPRESSED_OUTPUT=1
```
4. Now project compiled and work
P.S. Flags during running ./config with flags like ./config -s {PATH} or ./config -l {PATH} doesn’t help
