### ISSUE TITLE
The joy-3.0 could not extract the incomplete flows ? 

### ISSUE THREAD

**Issue by Anna-LC** [cisco/joy#204]
I want to use joy-master (joy 3.0) to extract the flows in the pcap, but I find that it cannot extract the information of incomplete tls flows. For example, the captured flow only  includes C2S Client Key Exchange, Change Cipher Spec, Encrypted Handshake Message packet, and S2C new session ticket, change cipher spec, Change Cipher Spec, Hello Request packet, Then the encrypted communication will be established. There is no Client Hello and Server Hello. For this flow, I cannot extract the tls metadata in Change Cipher Spec with joy-master now. But I test the joy-1.7, it is ok to extract the incomplete flows. I use the same command "./joy tls=1 bidir=1 ../../2.pcap |gunzip"  to run it.

Can you help me to solve it?

**Comment by bhudson33** [comment]
Could you send along the PCAP file producing the problem so we can take a look at it?

**Comment by Anna-LC** [comment]
This is the pcap file. 
[2.zip](https://github.com/cisco/joy/files/2540766/2.zip)
And the pcap file in 3.zip could not be extracted the handshake process information of TLS flow.
[3.zip](https://github.com/cisco/joy/files/2540772/3.zip)

Waiting for your reply!
Thank you so much!
