### ISSUE TITLE
Unused parameter error when building

### ISSUE THREAD

**Issue by Yilong94** [cisco/joy#224]
Hi all, I am currently building on a macOS Mojave (10.14.2) machine but I seem to be having some issue at building the package. When I executed

`make clean;make`

I encountered the following error. My OpenSSL version is 1.0.2q.

`../src/fp.c:98:33: error: unused parameter 'header' [-Werror,-Wunused-parameter]`
`                    const struct pcap_pkthdr *header, `
`                                             ^`
`1 error generated.`
`make[2]: *** [../src/libjoy_la-fp.lo] Error 1`
`make[1]: *** [all-recursive] Error 1`
`make: *** [all] Error 2`

Before that, I executed:

`./configure --enable-gzip --with-ssl-dir=/usr/local/ssl/`

but this did not seem to generate any error and the Makerfile is created.

Any help would be much appreciated. Thank you.

**Comment by tdjCisco** [comment]
Currently looking into this.

-Todd

**Comment by Yilong94** [comment]
FYI, I reverted to v3.0.3 and this version is working well with minor issues :). 

I will just put the minor issues I faced here in case it helps anyone:
* Issue 1: ld: library not found for -lgcc_s.10.5 --> found help [here](https://stackoverflow.com/questions/31936170/npm-the-ld-library-not-found-for-lgcc-s-10-5-on-on-os-x-el-capitan) and solved by executing
`cd /usr/local/lib`
`sudo ln -s ../../lib/libSystem.B.dylib libgcc_s.10.5.dylib`
* Issue 2: ld: library not found for -lcrypto --> solved with issue [#199](https://github.com/cisco/joy/issues/199)

**Comment by tdjCisco** [comment]
I've committed the change and you can build from the latest again.
