### ISSUE TITLE
Question about psk_key_exchange_modes extension

### ISSUE THREAD

**Issue by alonbright** [cisco/joy#231]
Hi,
I started to explore your DB a bit, and I found out that the content in the json of extension _psk_key_exchange_modes_ (extension 0x002d) is always empty, though it seems like from here:

https://github.com/cisco/joy/blob/4157222240994440c2f7835e699404a9e0f5fe53/fingerprinting/tls_fingerprint.py#L57

that you want to extract the value of that extension.
Am i missing something?

Thanks!

**Comment by banderson84** [comment]
Hi,

Yes, it is always missing... because of a bug I introduced into the fingerprint database post-processing. Thank you very much for pointing this out! I will push a fixed database soon.

Thanks,
Blake

**Comment by bhudson33** [comment]
blake has this been committed and fixed?

**Comment by seredvladislav** [comment]
Is there any updates? Bug has been fixed or not?

**Comment by banderson84** [comment]
Sorry, I forgot to close the issue. Yes, it was fixed about 5 months ago.
