### ISSUE TITLE
configure error on Mac: can't find openSSL libcrypto file

### ISSUE THREAD

**Issue by TornadoBoy** [cisco/joy#255]
I tried to build the latest version on my Mac and had no idea how to handle the configure error: 

> checking for EVP_EncryptInit in -lcrypto... no
> configure: error: in `/Users/xin/Desktop/joy':
> configure: error: can't find openSSL libcrypto file

My openssl version is 1.1.1b. I followed the instructions to download the OpenSSL tarball and run the config script.  I also tried to add _--with-ssl-dir=..._ which was also effortless.

**Comment by bhudson33** [comment]
configure is not finding libcrypto. Can you paste in the exact line you issued configure with? Also, locate the file libcrypto.a/libcrypto.so on your machine and paste that path here as well.

**Comment by TornadoBoy** [comment]
> configure is not finding libcrypto. Can you paste in the exact line you issued configure with? Also, locate the file libcrypto.a/libcrypto.so on your machine and paste that path here as well.

Thanks. I finally found the right location **_--with-ssl-dir=/usr/local/opt/openssl_** which is the homebrew installation path. Alternatively,  the following settings also work.

```
export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include"
```
