### ISSUE TITLE
When i ran the ./fingerprinter.py test.pcap, I am not getting any values. it's returning empty only

### ISSUE THREAD

**Issue by muthhus** [cisco/joy#259]
When i ran the ./fingerprinter.py test.pcap, I am not getting any values. it's returning empty only.

Thanks

**Comment by muthhus** [comment]
It's only working with your test pcap data. I assume that it might be formatted/implemented based on your test pcap file structure.

**Comment by bhudson33** [comment]
it appears that there may not be a TLS fingerprint in your PCAP file. Try this:

bin/joy fpx=1 <yourpcapfile> 

and see if the output contains a TLS fingerprint. If not then the PCAP file you have does not contain a TLS PCAP. if you run the same command on test/pcaps/tls12.pcap you will see a fingerprint is found.

if you have gzip option turned on, then pipe the output into zless
