### ISSUE TITLE
file opened but not closed.

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [cisco/joy#267]
file opened here:
https://github.com/cisco/joy/blob/5dd5b71bc1fe71ff0d0cf1b6263e6f5449cd622d/src/anon.c#L310

in lline 339, function returned but file is not closed yet:
https://github.com/cisco/joy/blob/5dd5b71bc1fe71ff0d0cf1b6263e6f5449cd622d/src/anon.c#L337-L340

**Comment by bhudson33** [comment]
accepted and fix will be made

**Comment by hdbui** [comment]
These are the same warning that was flagged by muse-dev.

Hoan
