### ISSUE TITLE
What happened to sleuthui?

### ISSUE THREAD

**Issue by Gelob** [cisco/joy#271]
What happened to sleuthui? I see it referenced in older Cisco live videos. Is running the webui from an older commit still relevant? Anything like that in the works again?

**Comment by bhudson33** [comment]
As we have progressed toward an automation pipeline around processing the results, we have kind of abandoned the UI aspect. I have not tried to see if the older UI code would work or not. There are no current plans to re-implement a UI into the Joy tool. Sorry.

**Comment by Gelob** [comment]
OK thank you, I did find the fingerprinting_ui.py tool which is something!
