### ISSUE TITLE
http is not an option listed in usage for src/joy.c

### ISSUE THREAD

**Issue by aradford123** [cisco/joy#42]
current usage message leaves out "http=1"  which is required for ohttp and ihttp headers

**Comment by bhudson33** [comment]
added to the usage output.

**Comment by bhudson33** [comment]
Adam,

I just pushed a fix for this.

Cheers,
Bill.

On Mar 26, 2017, at 11:20 PM, aradford123 <notifications@github.com<mailto:notifications@github.com>> wrote:


current usage message leaves out "http=1" which is required for ohttp and ihttp headers

**Comment by aradford123** [comment]
Awesome.. Thanks Bill.
