### ISSUE TITLE
Strange source addresses generated when all traffic is on local network

### ISSUE THREAD

**Issue by delgadod** [cisco/joy#54]
Hello,

I am using Joy to inspect various .pcap files that were generated by collecting network data on a Hadoop cluster. tcpdump was used and only packets on the local network - on the cluster - were collected.
When Joy is used on such .pcap files, instead of seeing various flows among the local network nodes ONLY, I see various other strange addresses, and no local flows as I'd expect.
![joy_options](https://cloud.githubusercontent.com/assets/25486506/26651815/e4407dcc-461b-11e7-9849-2f4427a12cfc.png)
Here I generate the .gz archive using joy from a .pcap file.
![tcpdumphadoop30](https://cloud.githubusercontent.com/assets/25486506/26651761/c1c3cf4c-461b-11e7-9323-c499a62d43fb.png)
Here you can see the contents of the .pcap in Wireshark

![query_output](https://cloud.githubusercontent.com/assets/25486506/26651762/c1c8684a-461b-11e7-9e5a-b3d93e285db5.png)
And yet, the output has addresses which are not seen in Wireshark at all.

Why does this occur?

**Comment by davidmcgrew** [comment]
Hi, I noticed that your wireshark screen grab shows "linux cooked capture" https://wiki.wireshark.org/SLL   I believe that someone contributed code to joy.c so that this pseudo-link header type is properly handled.
