### ISSUE TITLE
interface_list_get() for GNU/Linux doesn't set the active flag in ifl[i]

### ISSUE THREAD

**Issue by vijunag** [cisco/joy#60]
The interface_list_get() method doesn't set the active flag and the tool displays interfaces as down despite it being active.  The below patch should fix the issue. 

diff --git a/src/joy.c b/src/joy.c
index a4fa5bd..488f05e 100644
--- a/src/joy.c
+++ b/src/joy.c
``
@@ -233,6 +233,7 @@ static unsigned int interface_list_get (struct interface ifl[IFL_MAX]) {
                       if (ioctl(sock, SIOCGIFHWADDR, &ifr) == 0) {
                           memcpy(ifl[i].mac_addr, ifr.ifr_hwaddr.sa_data, 6);
                           strncpy(ifl[i].name, it->ifr_name, IFNAMSIZ);
+                       ifl[i].active = 1;
                           i++;
                           break;
                       }
``

**Comment by bhudson33** [comment]
This code is old and the function has been re-written to use libpcap to find interfaces. The active flag is no longer used and the display output no longer shows active/inactive.
