### ISSUE TITLE
Byte distribution

### ISSUE THREAD

**Issue by vinayakumarr** [cisco/joy#63]
I would like to know how byte distribution is calculated. Is it any statistical measure applied like mean, standard deviation. Whenever we give a Pcap file and if we select 

./query.py capture.gz --select "bd" 

it will give 256 values. I would like to know how it is calculated?

**Comment by davidmcgrew** [comment]
Hi Vinay,

**Comment by vinayakumarr** [comment]
Is there any option to extract the raw TCP flow payload data from pcap file (like 11 slides from https://www.blackhat.com/docs/us-15/materials/us-15-Wang-The-Applications-Of-Deep-Learning-On-Traffic-Identification.pdf).

**Comment by vinayakumarr** [comment]
Otherwise, payload of joy is similar to the (11 slides from https://www.blackhat.com/docs/us-15/materials/us-15-Wang-The-Applications-Of-Deep-Learning-On-Traffic-Identification.pdf).
