### ISSUE TITLE
what is “map.h” doing

### ISSUE THREAD

**Issue by flowsand88** [cisco/joy#82]
Thanks for your attention.
I am troubled verymuch. what is file “map.h” doing?

for example when he define EVAL(...), he writed like this :
     #define EVAL0(...) __VA_ARGS__
     #define EVAL1(...) EVAL0 (EVAL0 (EVAL0 (__VA_ARGS__)))
     #define EVAL2(...) EVAL1 (EVAL1 (EVAL1 (__VA_ARGS__)))
     #define EVAL3(...) EVAL2 (EVAL2 (EVAL2 (__VA_ARGS__)))
     #define EVAL4(...) EVAL3 (EVAL3 (EVAL3 (__VA_ARGS__)))
     #define EVAL(...)  EVAL4 (EVAL4 (EVAL4 (__VA_ARGS__)))
why? what is he doing?
In file "feature.h" he define so many macors. Only arguments "wht\example\dns\tls\..." is resolved in macors "config_all_features_bool(feature_list);" others are resolved in function "config_parse_command"
why he do this? how "config_all_features_bool" worked? what is this argument "feature_list"?

thanks for your attention again.

**Comment by davidmcgrew** [comment]
map.h implements a recursive C preprocessor macro which performs an operation on each element of a list.   See https://github.com/swansontec/map-macro

David

**Comment by flowsand88** [comment]
@davidmcgrew 
thank you very much for answering my question.
i am quiet understanded now.
